package io.github.kardane.jarvisminecraft.common.brain;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import io.github.kardane.jarvisminecraft.common.config.ConfigManager;
import io.github.kardane.jarvisminecraft.common.config.JarvisConfig;
import io.github.kardane.jarvisminecraft.common.logging.JarvisEvents;
import io.github.kardane.jarvisminecraft.common.logging.JarvisFields;
import io.github.kardane.jarvisminecraft.common.logging.JarvisLog;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Stream;

public final class AsyncConversationArchive
    implements AutoCloseable {
    public static final String DIRECTORY_NAME = "conversations";
    public static final String README_FILE = "README.md";

    private static final int QUEUE_CAPACITY = 512;
    private static final DateTimeFormatter FILE_TIME =
        DateTimeFormatter.ofPattern(
            "uuuuMMdd'T'HHmmss.SSS'Z'"
        ).withZone(ZoneOffset.UTC);

    private static final String README = """
        # JARVIS Conversation Archive

        This directory contains optional JSONL conversation archives generated by
        JarvisMinecraft when jarvis.conversation-archive.enabled is true.

        Each line is one user or assistant message with:
        - schemaVersion
        - at
        - serverId
        - requesterUuid
        - sessionId
        - requestId
        - origin
        - role (USER or ASSISTANT)
        - text

        Tool results, hidden prompts/policy, reasoning, persona/knowledge content,
        provider credentials, and API keys are not written to this archive.

        Files are rotated and pruned according to the configured file-size and
        file-count limits. This README may be replaced manually and is never used
        as model context.
        """;

    private final String serverId;
    private final Path directory;
    private final ConfigManager configManager;
    private final Clock clock;
    private final JarvisLog log;
    private final Gson gson = new GsonBuilder()
        .disableHtmlEscaping()
        .create();
    private final ThreadPoolExecutor executor;
    private final AtomicBoolean closed =
        new AtomicBoolean();
    private final AtomicBoolean queueWarningLogged =
        new AtomicBoolean();

    private Path activeFile;

    public AsyncConversationArchive(
        String serverId,
        Path configRoot,
        ConfigManager configManager,
        Clock clock,
        JarvisLog log
    ) {
        if (serverId == null || serverId.isBlank()) {
            throw new IllegalArgumentException(
                "serverId must not be blank."
            );
        }
        this.serverId = serverId;
        this.directory = Objects.requireNonNull(
            configRoot,
            "configRoot"
        ).toAbsolutePath().normalize()
            .resolve(DIRECTORY_NAME);
        this.configManager = Objects.requireNonNull(
            configManager,
            "configManager"
        );
        this.clock = Objects.requireNonNull(clock, "clock");
        this.log = Objects.requireNonNull(log, "log");
        this.executor = new ThreadPoolExecutor(
            1,
            1,
            0L,
            TimeUnit.MILLISECONDS,
            new ArrayBlockingQueue<>(QUEUE_CAPACITY),
            runnable -> {
                Thread thread = new Thread(
                    runnable,
                    "jarvis-conversation-archive"
                );
                thread.setDaemon(true);
                return thread;
            },
            new ThreadPoolExecutor.AbortPolicy()
        );
    }

    public void record(
        UUID requesterUuid,
        UUID sessionId,
        ConversationEntry entry
    ) {
        Objects.requireNonNull(
            requesterUuid,
            "requesterUuid"
        );
        Objects.requireNonNull(sessionId, "sessionId");
        Objects.requireNonNull(entry, "entry");

        JarvisConfig.ConversationArchive settings =
            configManager.current().conversationArchive();
        if (!settings.enabled() || closed.get()) {
            return;
        }

        ArchiveRecord record = toArchiveRecord(
            requesterUuid,
            sessionId,
            entry
        );
        if (record == null) {
            return;
        }

        try {
            executor.execute(() ->
                writeRecord(settings, record)
            );
            queueWarningLogged.set(false);
        } catch (RejectedExecutionException failure) {
            if (
                !closed.get()
                    && queueWarningLogged.compareAndSet(
                        false,
                        true
                    )
            ) {
                log.warn(
                    JarvisEvents.CONVERSATION_ARCHIVE_DROPPED,
                    JarvisFields.of(
                        "reason", "queue_full"
                    )
                );
            }
        }
    }

    public CompletionStage<Void> flushAsync() {
        if (closed.get()) {
            return CompletableFuture.failedFuture(
                new IllegalStateException(
                    "Conversation archive is closed."
                )
            );
        }

        CompletableFuture<Void> flushed =
            new CompletableFuture<>();
        try {
            executor.execute(() ->
                flushed.complete(null)
            );
        } catch (RejectedExecutionException failure) {
            flushed.completeExceptionally(failure);
        }
        return flushed;
    }

    private ArchiveRecord toArchiveRecord(
        UUID requesterUuid,
        UUID sessionId,
        ConversationEntry entry
    ) {
        if (
            entry
                instanceof ConversationEntry.UserMessage user
        ) {
            if (isProactive(user.origin())) {
                return null;
            }
            return new ArchiveRecord(
                1,
                user.at().toString(),
                serverId,
                requesterUuid.toString(),
                sessionId.toString(),
                user.requestId().toString(),
                user.origin(),
                "USER",
                user.text()
            );
        }
        if (
            entry
                instanceof ConversationEntry.AssistantMessage assistant
        ) {
            if (isProactive(assistant.origin())) {
                return null;
            }
            return new ArchiveRecord(
                1,
                assistant.at().toString(),
                serverId,
                requesterUuid.toString(),
                sessionId.toString(),
                assistant.requestId().toString(),
                assistant.origin(),
                "ASSISTANT",
                assistant.text()
            );
        }
        return null;
    }

    private boolean isProactive(String origin) {
        return "PROACTIVE".equalsIgnoreCase(origin)
            || "PROACTIVE_CANDIDATE".equalsIgnoreCase(
                origin
            );
    }

    private void writeRecord(
        JarvisConfig.ConversationArchive settings,
        ArchiveRecord record
    ) {
        try {
            ensureDirectory();
            String line = gson.toJson(record) + "\n";
            byte[] bytes = line.getBytes(
                StandardCharsets.UTF_8
            );
            if (bytes.length > settings.maxFileBytes()) {
                log.warn(
                    JarvisEvents.CONVERSATION_ARCHIVE_DROPPED,
                    JarvisFields.of(
                        "reason", "record_too_large"
                    )
                );
                return;
            }

            Path target = activeFile(
                settings,
                bytes.length
            );
            Files.writeString(
                target,
                line,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.APPEND,
                StandardOpenOption.WRITE
            );
            prune(settings.maxFiles());
        } catch (RuntimeException | IOException failure) {
            log.error(
                JarvisEvents.CONVERSATION_ARCHIVE_FAILED,
                failure,
                JarvisFields.of(
                    "directory",
                    DIRECTORY_NAME
                )
            );
        }
    }

    private void ensureDirectory() throws IOException {
        Files.createDirectories(directory);
        if (Files.isSymbolicLink(directory)) {
            throw new IllegalStateException(
                "Conversation archive directory must not be a symbolic link."
            );
        }

        Path readme = directory.resolve(README_FILE);
        if (
            !Files.exists(
                readme,
                LinkOption.NOFOLLOW_LINKS
            )
        ) {
            try {
                Files.writeString(
                    readme,
                    README,
                    StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE_NEW,
                    StandardOpenOption.WRITE
                );
            } catch (
                java.nio.file.FileAlreadyExistsException ignored
            ) {
                // Another startup/write created it first.
            }
        }
    }

    private Path activeFile(
        JarvisConfig.ConversationArchive settings,
        int incomingBytes
    ) throws IOException {
        if (
            activeFile != null
                && Files.isRegularFile(
                    activeFile,
                    LinkOption.NOFOLLOW_LINKS
                )
                && !Files.isSymbolicLink(activeFile)
                && Files.size(activeFile) + incomingBytes
                    <= settings.maxFileBytes()
        ) {
            return activeFile;
        }

        activeFile = directory.resolve(
            "conversation-"
                + FILE_TIME.format(clock.instant())
                + "-"
                + UUID.randomUUID()
                    .toString()
                    .substring(0, 8)
                + ".jsonl"
        );
        return activeFile;
    }

    private void prune(int maxFiles) throws IOException {
        List<Path> files;
        try (Stream<Path> stream = Files.list(directory)) {
            files = stream
                .filter(path ->
                    Files.isRegularFile(
                        path,
                        LinkOption.NOFOLLOW_LINKS
                    )
                )
                .filter(path ->
                    !Files.isSymbolicLink(path)
                )
                .filter(path ->
                    path.getFileName()
                        .toString()
                        .startsWith("conversation-")
                )
                .filter(path ->
                    path.getFileName()
                        .toString()
                        .endsWith(".jsonl")
                )
                .sorted(
                    Comparator.comparing(
                        this::lastModifiedSafely
                    )
                )
                .toList();
        }

        int remaining = files.size();
        for (Path candidate : files) {
            if (remaining <= maxFiles) {
                break;
            }
            if (candidate.equals(activeFile)) {
                continue;
            }
            if (Files.deleteIfExists(candidate)) {
                remaining -= 1;
            }
        }
    }

    private Instant lastModifiedSafely(Path path) {
        try {
            return Files.getLastModifiedTime(path)
                .toInstant();
        } catch (IOException ignored) {
            return Instant.EPOCH;
        }
    }

    @Override
    public void close() {
        if (closed.compareAndSet(false, true)) {
            executor.shutdown();
        }
    }

    private record ArchiveRecord(
        int schemaVersion,
        String at,
        String serverId,
        String requesterUuid,
        String sessionId,
        String requestId,
        String origin,
        String role,
        String text
    ) {
    }
}
